dietCheck/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('home.urls', namespace="home")),
    path('admin/', admin.site.urls),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home , name='index'),

    path("login/", views.login_request, name='login'),
    path('register/', views.register, name='register'),
    path("logout/", views.logout_request, name='logout'),

    path('optum/', views.optum_calc , name='optum'),
    path('optum_drug_predict/', views.optum_drug_predict , name='optum-api'),


    path('calorie/', views.cal_calc , name='cal-calc'),
    path('profile/', views.profile, name='profile'),
    path('diet/', views.diet, name='diet'),
    path('update/', views.update , name='update'),
    path('chart/', views.chart , name='chart'),

    #path('about/', views.about , name='about'),
    #path('blog/', views.blog , name='blog'),
    #path('contact/', views.contact , name='contact'),
    #path('services/', views.services, name='services'),
    #path('service/<int:num>/', views.service_num, name='service'),
    #path('work/', views.work, name='work'),
    #path('work/add', views.add_work, name='add-work'),
    #path('work/list', views.work_list , name='work-list'),
    #path('work/delete/<int:pk>', views.work_delete , name='work-del'),

]

templates/answer.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title> Diet Check | Result </title>
{% endblock %}

{% block body %}
  <section class="contact-section" style = "padding: 10px 0 140px;">
            <div class="container">

                <div class="row">

                    <div class="col-lg-7">
                        <br>
                        <h2 class="contact-title"> Diet Suggestion for you. </h2>
                          Hello dear..
                        <br>
                            We have received the following data -
                            <br>
                            <div class="row">
                                <div class="col-3">
                                        Gender
                                </div>
                                <div class="col-7">
                                      {{ gender }}
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-3">
                                        Age
                                </div>
                                <div class="col-7">
                                        {{ age }} years
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-3">
                                        Height
                                </div>
                                <div class="col-7">
                                      {{ height }} cms
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-3">
                                        Weight
                                </div>
                                <div class="col-7">
                                        {{ weight }} kgs
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-3">
                                        BMI
                                </div>
                                <div class="col-7">
                                      {{ bmi }}
                                </div>
                            </div>

                            <br>
Our results show that<br>
                            You should take around {{ ans }} Kcal per day to keep yourself fit and healthy.
<br>
                        If you haven't created an account at <strong> DietCheck </strong> yet,
                        <br>
                        please register below and monitor your daily diet chart.

                            <div class="form-group mt-5">
                                <button type="submit" class="button button-contactForm boxed-btn"> Register </button>
                            </div>

                    </div>
                    <div class="col-lg-5"  >
                        <img src="{% static 'img/f3.jpg' %}" style="height: 350px; opacity: 0.8;" height=300px>   </img>

                    </div>
                </div>
            </div>
</section>
{% endblock %}

templates/answer2.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title> Optum Hackathon | Result </title>
{% endblock %}

{% block body %}
  <section class="contact-section" style = "padding: 10px 0 140px;">
            <div class="container">

                <div class="row">

                    <div class="col-lg-7">
                        <br>
                        <h2 class="contact-title"> Drugs and Dosage Suggestion-  </h2>
                          Hello dear..
                        <br>
                            We have received the following data -
                            <br>
                            <div class="row">
                                <div class="col-3"> Gender  </div>
                                <div class="col-7">  {{ gender }}   </div>
                            </div>

                            <div class="row">
                                <div class="col-3"> Age </div>
                                <div class="col-7"> {{ age }} years  </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-3">  Height   </div>
                                <div class="col-7">   {{ height }} inches    </div>
                            </div>

                            <div class="row">
                                <div class="col-3">  Weight  </div>
                                <div class="col-7">  {{ weight }} lbs  </div>
                            </div>
                            <div class="row">
                                <div class="col-3">  Cancer Type </div>
                                <div class="col-7">  {{ cancer }}  </div>
                            </div>

                            <br>  Our results - <br>
                            Recommended Drug : {{ drug }}  <br>
                            Recommended Dosage : {{ dose }} mg
                            <br>
                            <br>
                            <br>

                        If you haven't created an account at <strong> DietCheck </strong> yet,
                        <br>
                        please register below and monitor your daily diet chart.

                            <div class="form-group mt-5">
                                <button type="submit" class="button button-contactForm boxed-btn"> Register </button>
                            </div>

                    </div>
                    <div class="col-lg-5"  >
                        <img src="{% static 'img/f3.jpg' %}" style="height: 350px; opacity: 0.8;" height=300px>   </img>

                    </div>
                </div>
            </div>
</section>
{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
{% block head %}
  <title> Diet Check </title>
{% endblock %}
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.ico">

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/progressbar_barfiller.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animated-headline.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body class="full-wrapper">
    <!-- ? Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <!--img src="assets/img/logo/loder.png" alt=""-->
                      Diet Check
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start-->
    <header>
        <!-- Header Start -->
        <div class="header-area ">
            <div class="main-header header-sticky">
                <div class="container-fluid">
                    <div class="menu-wrapper d-flex align-items-center justify-content-between">
                        <div class="header-left d-flex align-items-center">
                            <!-- Logo -->
                            <div class="logo">
                                <a href="{% url 'home:index' %}"><img src="{% static 'img/logo.png' %}" alt="" height="120px"></a>
                            </div>
                            <!-- Main-menu -->
                            <div class="main-menu  d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <!--li><a href="{% url 'home:index' %}">Home</a></li>
                                        <li><a href="{% url 'home:cal-calc' %}"> Calorie Requiremnt </a></li>
                                        <li><a href="{% url 'home:chart' %}"> My Calorie Chart </a></li-->
                                        <li><a href="{% url 'home:optum' %}"> Optum Drug Predictor </a></li>

                                        <li><a href="#"> Account </a>
                                            <ul class="submenu">
                                                {% if request.user.is_authenticated %}
                                                    <li><a href="{% url 'home:logout' %}"> Log Out </a></li>
                                                    <li><a href="{% url 'home:register' %}"> Register </a></li>
                                                    <li><a href="{% url 'home:profile' %}"> Profile </a></li>
                                                {% else %}
                                                    <li><a href="{% url 'home:login' %}"> Log in </a></li>
                                                    <li><a href="{% url 'home:register' %}"> Register </a></li>
                                                {% endif %}
                                            </ul>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="header-right1 d-flex align-items-center">
                            <!-- Social -->
                            <div class="header-social d-none d-md-block">
                                <a href="#"><i class="fab fa-twitter"></i></a>
                                <a href="https://bit.ly/sai4ull"><i class="fab fa-facebook-f"></i></a>
                            </div>
                            <!-- Search Box -->
                            <div class="search d-none d-md-block">
                                <ul class="d-flex align-items-center">
                                    <li class="mr-15">
                                        <div class="nav-search search-switch">
                                            <i class="ti-search"></i>
                                        </div>
                                    </li>
                                    {% if request.user.is_authenticated %}
                                        <li class="mr-15">
                                            <a href="#" style = "color: #0d7331;" > Hello {{ user.username }} </a>
                                        </li>

                                    {% endif %}
                                    </ul>
                            </div>
                        </div>
                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Header End -->
    </header>
    <!-- header end -->
    <main>
        <!--? Hero Area Start-->
        <div class="container-fluid">
            <div class="slider-area">
                <!-- Mobile Device Show Menu-->
                <div class="header-right2 d-flex align-items-center">
                    <!-- Social -->
                    <div class="header-social  d-block d-md-none">
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="https://bit.ly/sai4ull"><i class="fab fa-facebook-f"></i></a>

                    </div>
                    <!-- Search Box -->
                    <div class="search d-block d-md-none" >
                        <ul class="d-flex align-items-center">
                            <li class="mr-15">
                                <div class="nav-search search-switch">
                                    <i class="ti-search"></i>
                                </div>
                            </li>

                            {% if request.user.is_authenticated %}
                            <li>

                                    Hello {{ user.username }}

                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                <!-- /End mobile  Menu-->
            </div>
        </div>
        <!-- End Hero -->
        <!--? Popular Items Start -->

<!-- Popular Items End -->
<!--? New Arrival Start -->

    {% block body %}
    <h1>  This is the base template. :)   </h1>
    {% endblock %}

<!--? Services Area End -->
</main>

<footer>
    <!-- Footer Start-->
    <div class="footer-area footer-padding">
        <div class="container-fluid ">
            <div class="row d-flex justify-content-between">
                <div class="col-xl-3 col-lg-3 col-md-8 col-sm-8">
                 <div class="single-footer-caption mb-50">
                   <div class="single-footer-caption mb-30">
                      <!-- logo -->
                      <div class="footer-logo mb-35">
                       <a href="index.html"><img src="assets/img/logo/logo2_footer.png" alt=""></a>
                   </div>
                   <div class="footer-tittle">
                       <div class="footer-pera">
                           <p>Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla.</p>
                       </div>
                   </div>
                   <!-- social -->
                   <div class="footer-social">
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="https://bit.ly/sai4ull"><i class="fab fa-facebook-f"></i></a>
                    <a href="#"><i class="fab fa-pinterest-p"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-2 col-lg-2 col-md-4 col-sm-4">
        <div class="single-footer-caption mb-50">
            <div class="footer-tittle">
                <h4>Quick links</h4>
                <ul>
                    <li><a href="#">Image Licensin</a></li>
                    <li><a href="#">Style Guide</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-xl-2 col-lg-2 col-md-4 col-sm-4">
        <div class="single-footer-caption mb-50">
            <div class="footer-tittle">
                <h4>Shop Category</h4>
                <ul>
                    <li><a href="#">Image Licensin</a></li>
                    <li><a href="#">Style Guide</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-xl-2 col-lg-2 col-md-4 col-sm-4">
        <div class="single-footer-caption mb-50">
            <div class="footer-tittle">
                <h4>Pertners</h4>
                <ul>
                    <li><a href="#">Image Licensin</a></li>
                    <li><a href="#">Style Guide</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-4">
        <div class="single-footer-caption mb-50">
            <div class="footer-tittle">
                <h4>Get in touch</h4>
                <ul>
                    <li><a href="#">(89) 982-278 356</a></li>
                    <li><a href="#">demo@colorlib.com</a></li>
                    <li><a href="#">67/A, Colorlib, Green road, NYC</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
</div>
</div>
<!-- footer-bottom area -->
<div class="footer-bottom-area">
    <div class="container">
        <div class="footer-border">
           <div class="row d-flex align-items-center">
               <div class="col-xl-12 ">
                   <div class="footer-copy-right text-center">
                       <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                          Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                          <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!-- Footer End-->
</footer>
<!--? Search model Begin -->
<div class="search-model-box">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-btn">+</div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Searching key.....">
        </form>
    </div>
</div>
<!-- Search model end -->
<!-- Scroll Up -->
<div id="back-top" >
    <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
</div>

<!-- JS here -->
<!-- Jquery, Popper, Bootstrap -->
<script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- Slick-slider , Owl-Carousel ,slick-nav -->
<script src="./assets/js/owl.carousel.min.js"></script>
<script src="./assets/js/slick.min.js"></script>
<script src="./assets/js/jquery.slicknav.min.js"></script>

<!-- One Page, Animated-HeadLin, Date Picker -->
<script src="./assets/js/wow.min.js"></script>
<script src="./assets/js/animated.headline.js"></script>
<script src="./assets/js/jquery.magnific-popup.js"></script>
<script src="./assets/js/gijgo.min.js"></script>

<!-- Nice-select, sticky,Progress -->
<script src="./assets/js/jquery.nice-select.min.js"></script>
<script src="./assets/js/jquery.sticky.js"></script>
<script src="./assets/js/jquery.barfiller.js"></script>

<!-- counter , waypoint,Hover Direction -->
<script src="./assets/js/jquery.counterup.min.js"></script>
<script src="./assets/js/waypoints.min.js"></script>
<script src="./assets/js/jquery.countdown.min.js"></script>
<script src="./assets/js/hover-direction-snake.min.js"></script>

<!-- contact js -->
<script src="./assets/js/contact.js"></script>
<script src="./assets/js/jquery.form.js"></script>
<script src="./assets/js/jquery.validate.min.js"></script>
<script src="./assets/js/mail-script.js"></script>
<script src="./assets/js/jquery.ajaxchimp.min.js"></script>

<!-- Jquery Plugins, main Jquery -->
<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

templates/calorie_calc.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title> Diet Check | Calorie Calculator </title>
{% endblock %}

{% block body %}
<section class="contact-section" style = "padding: 10px 0 140px;">
            <div class="container">

                <div class="row">
                    <div class="col-12">
                        <h2 class="contact-title"> Calorie Calculator </h2>
                    </div>
                    <div class="col-lg-7">
                        <form class="form-contact contact_form" action="" method="post" id="contactForm">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-3">
                                    <div class="form-group">
                                        <label for="gender" style="font-size: 16px;"> Gender </label>
                                    </div>
                                </div>
                                <div class="col-7">
                                    <div class="form-group">
                                        <select class="form-control" name="gender" id="gender">
                                            <option value=1>   Female  </option>
                                            <option value=0>  Male  </option>
					                    </select>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-3">
                                    <div class="form-group">
                                        <label for="age" style="font-size: 16px;"> Birth Date </label>
                                    </div>
                                </div>
                                <div class="col-7">
                                    <div class="form-group">
                                        <input class="form-control" name="age" id="subject" type="date"
                                        placeholder="">
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-3">
                                    <div class="form-group">
                                        <label for="age" style="font-size: 16px;"> Height(in cms) </label>
                                    </div>
                                </div>
                                <div class="col-7">
                                    <div class="form-group">
                                        <input class="form-control" name="height" id="subject" type="number" min=100  max=250>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-3">
                                    <div class="form-group">
                                        <label for="age" style="font-size: 16px;"> Weight(in kgs) </label>
                                    </div>
                                </div>
                                <div class="col-7">
                                    <div class="form-group">
                                        <input class="form-control" name="weight" id="subject" type="number"  min=20  max=200>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-3">
                                    <div class="form-group" >
                                        <label for="activity" style="font-size: 16px;"> Physical Activity Level </label>
                                    </div>
                                </div>
                                <div class="col-7">
                                    <div class="form-group">
                                        <select class="form-control" name="active" id="activity">
                                            <option value="High">   Highly Active  </option>
                                            <option value="Mid">  Moderate Active  </option>
                                            <option value="Low">   Less Active </option>
					                    </select>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group mt-5">
                                <button type="submit" class="button button-contactForm boxed-btn"> Calculate </button>
                            </div>
                        </form>
                    </div>
                    <div class="col-lg-5"  >
                        <img src="{% static 'img/f3.jpg' %}" style="height: 350px; opacity: 0.8;" height=350px>   </img>

                    </div>
                </div>
            </div>
</section>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title> Diet Check | Profile </title>
{% endblock %}

{% block body %}
  <section class="contact-section" style = "padding: 10px 0 140px;">
            <div class="container">

                <div class="row">
                    <div class="col-12">
                        <h2 class="contact-title"> My Profile </h2>
                    </div>
                    <div class="col-lg-7">

                            <div class="row">
                                <div class="col-3">
                                        Name
                                </div>
                                <div class="col-7">
                                     {{ data.person.name }}
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-3">
                                        Gender
                                </div>
                                <div class="col-7">
                                      {{ data.person.gender }}
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-3">
                                        Age
                                </div>
                                <div class="col-7">
                                      25 years
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-3">
                                        Height
                                </div>
                                <div class="col-7">
                                        165 cms
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-3">
                                      Weight
                                </div>
                                <div class="col-7">
                                    65 kgs
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-3">
                                      Body Mass Index
                                </div>
                                <div class="col-7">
                                       23.88
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-3">
                                        Activity Level
                                </div>
                                <div class="col-7">
                                        Highly Active
                                </div>
                            </div>
Our results show that  <br>
You should take around 2200 Kcal per day to keep yourself fit and healthy.
                            <div class="form-group mt-5">
                               <a href = "{% url 'home:update' %}">
                                <button type="submit" class="button button-contactForm boxed-btn"> Update Today's Diet </button>
                               </a>
                            </div>

                    </div>
                    <div class="col-lg-5"  >
                        <img src="{% static 'img/f3.jpg' %}" style="height: 350px; opacity: 0.8;" height=350px>   </img>

                    </div>
                </div>
                </div>
            </div>
</section>
{% endblock %}